### PR TITLE
[Galactic] Backport github actions CI

### PR DESCRIPTION
**Pull request by sloretz**
@chapulina mind taking a look?

Ubuntu Focal with ROS Galactic: testing Gazebo Citadel, Edifice (only because ROS Galactic pairs with it in REP 2000), and Fortress.

### CODE REVIEW

**Comment by chapulina** [comment]
It looks like all jobs are using Citadel, because there's no logic to choose different SDF versions. Let me rebase #8 onto this to see if I can get a different version on each job.

**Review by chapulina — APPROVED** [review]
LGTM! The only change I made to this file on #8 was `s/gazebo/gz` - I know I was the one who originally used "gazebo", sorry about that.

**Comment by sloretz** [comment]
> LGTM! The only change I made to this file on https://github.com/ros/sdformat_urdf/pull/8 was s/gazebo/gz

I pulled the change from your branch to this one. I'll retarget #8 so I don't accidentally close it this time when I merge (hopefully that doesn't do anything worse :crossed_fingers:)

**Comment by sloretz** [comment]
> LGTM! The only change I made to this file on https://github.com/ros/sdformat_urdf/pull/8 was s/gazebo/gz

I pulled the change from your branch to this one. I'll retarget #8 so I don't accidentally close it this time when I merge (hopefully that doesn't do anything worse :crossed_fingers:)

**Pull request merged**
