### PR TITLE
ign to gz migration

### PR DESCRIPTION
**Pull request by quarkytale**
Followed the depreciation warnings and migration docs to migrate to gz namespace

### CODE REVIEW

**Comment by azeey** [comment]
It should now be possible to use the `gz` namespace and headers in Fortress with packages from packages.ros.org. @quarkytale can you try rerunning the CI?

**Comment by quarkytale** [comment]
@osrf-jenkins run tests please

**Comment by quarkytale** [comment]
@Mergifyio refresh

**Comment by quarkytale** [comment]
@Mergifyio rebase

**Review by azeey — APPROVED** [review]

**Pull request merged**
