### PR TITLE
Fix Humble / Rolling build

### PR DESCRIPTION
**Pull request by chapulina**
* Broken off #8 and targeted at `ros2`

This PR has the bare minimum to get GitHub actions running and passing for the `ros2` branch.

* Update from `sdformat9` to `sdformat12`. Version 12 is the first to be supported on Jammy.
* The header moves are needed for `cpplint` to pass on Humble
* While moving the headers, I went ahead and made them narrower to speed up compilation

### CODE REVIEW

**Comment by sloretz** [comment]
Looks like the `sdformat12` rosdep key needs an entry on Jammy

https://github.com/ros/rosdistro/blob/8db58d767c12ffca910ccefd2068765cf11bcb63/rosdep/base.yaml#L7076-L7080

```
13:05:37 Traceback (most recent call last):
13:05:37   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 306, in <module>
13:05:37     main()
13:05:37   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 138, in main
13:05:37     debian_pkg_names_building = resolve_names(build_depends, **context)
13:05:37   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 289, in resolve_names
13:05:37     resolved_names = resolve_for_os(
13:05:37   File "/usr/lib/python3/dist-packages/rosdep2/catkin_support.py", line 91, in resolve_for_os
13:05:37     inst_key, rule = d.get_rule_for_platform(os_name, os_version, os_installers, default_os_installer)
13:05:37   File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 132, in get_rule_for_platform
13:05:37     raise ResolutionError(rosdep_key, self.data, os_name, os_version, 'No definition of [%s] for OS version [%s]' % (rosdep_key, os_version))
13:05:37 rosdep2.lookup.ResolutionError: No definition of [sdformat12] for OS version [jammy]
13:05:37 	rosdep key : sdformat12
13:05:37 	OS name    : ubuntu
13:05:37 	OS version : jammy
13:05:37 	Data:
13:05:37 debian:
13:05:37 		  buster:
13:05:37 		  - libsdformat12-dev
13:05:37 		ubuntu:
13:05:37 		  focal:
13:05:37 		  - libsdformat12-dev
```

**Comment by chapulina** [comment]
> Looks like the sdformat12 rosdep key needs an entry on Jammy

Ouch, my bad, here we go:

* https://github.com/ros/rosdistro/pull/33459

**Comment by chapulina** [comment]
Rebased on top of #10

**Comment by chapulina** [comment]
Ouch 😕  @sloretz I had updated this PR to have only the source code updates

**Comment by sloretz** [comment]
Ah ooops I didn't mean to close this, and I can't seem to reopen it. I deleted the branch `sloretz__ci_focal_jammy` after merging #10. That seems to put this PR in a bad state since it was targeting that branch. I can't even re-target it to the `ros2` branch :(

**Comment by chapulina** [comment]
haha no worries, I can open a new PR

**Comment by chapulina** [comment]
* Continues in https://github.com/ros/sdformat_urdf/pull/12

**Pull request closed without merging**
